"""Initial migration

Revision ID: dc6abffab8a1
Revises: 
Create Date: 2024-12-17 14:20:26.044251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6abffab8a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.Column('ROA_C_before_interest_and_depreciation_before_interest', sa.Float(), nullable=True),
    sa.Column('ROA_A_before_interest_and_Percent_after_tax', sa.Float(), nullable=True),
    sa.Column('ROA_B_before_interest_and_depreciation_after_tax', sa.Float(), nullable=True),
    sa.Column('Operating_Gross_Margin', sa.Float(), nullable=True),
    sa.Column('Tax_rate__A', sa.Float(), nullable=True),
    sa.Column('Net_Value_Per_Share__B', sa.Float(), nullable=True),
    sa.Column('Net_Value_Per_Share__A', sa.Float(), nullable=True),
    sa.Column('Net_Value_Per_Share__C', sa.Float(), nullable=True),
    sa.Column('Persistent_EPS_in_the_Last_Four_Seasons', sa.Float(), nullable=True),
    sa.Column('Current_Ratio', sa.Float(), nullable=True),
    sa.Column('Quick_Ratio', sa.Float(), nullable=True),
    sa.Column('Debt_ratio_Percent', sa.Float(), nullable=True),
    sa.Column('Net_worth/Assets', sa.Float(), nullable=True),
    sa.Column('Operating_profit/Paid-in_capital', sa.Float(), nullable=True),
    sa.Column('Net_profit_before_tax/Paid-in_capital', sa.Float(), nullable=True),
    sa.Column('Working_Capital_to_Total_Assets', sa.Float(), nullable=True),
    sa.Column('Quick_Assets/Current_Liability', sa.Float(), nullable=True),
    sa.Column('Current_Liability_to_Assets', sa.Float(), nullable=True),
    sa.Column('Total_income/Total_expense', sa.Float(), nullable=True),
    sa.Column('Current_Liability_to_Current_Assets', sa.Float(), nullable=True),
    sa.Column('Net_Income_to_Total_Assets', sa.Float(), nullable=True),
    sa.Column('Equity_to_Liability', sa.Float(), nullable=True),
    sa.Column('Cash_Ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_data')
    # ### end Alembic commands ###
